[licenses]
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "Unlicense OR MIT",
    "MIT OR Apache-2.0",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "GPL-2.0",
    "GPL-3.0",
    "Unicode-3.0",
    "Apache-2.0 OR MIT",
]

# Deny GPL licenses that require copyleft
deny = [
    "GPL-2.0-only",
    "GPL-3.0-only",
    "AGPL-3.0",
]

# Allow unknown licenses for now (can be tightened later)
allow-unknown-licenses = true

[licenses.copyleft]
# Allow some copyleft licenses but be explicit about it
allow = ["LGPL-2.1", "LGPL-3.0"]

[advisories]
# Ignore unmaintained crate warnings
ignore = [
    "RUSTSEC-2024-0388", # derivative
    "RUSTSEC-2024-0436", # paste
]

[advisories.unmaintained]
# Allow unmaintained crates (they still work, just not actively maintained)
warn = "warn"
ignore = [
    "RUSTSEC-2024-0388", # derivative
    "RUSTSEC-2024-0436", # paste
]
