[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "Zlib",
    "CC0-1.0",
    "Unicode-3.0",
    "0BSD",
    "CDLA-Permissive-2.0",
    "OpenSSL",
]

[advisories]
ignore = [
    "RUSTSEC-2024-0388",
    "RUSTSEC-2024-0436",
]
