global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Bridge Router application metrics
  - job_name: 'bridge-router'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Bridge Router app
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana (optional - for monitoring Grafana itself)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis (if you want to monitor Redis directly)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    # Note: Redis exporter would be needed for this to work

  # PostgreSQL (if you want to monitor PostgreSQL directly)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    # Note: PostgreSQL exporter would be needed for this to work
